サインアップAPIの追加
givery-bootcamp/dena-2024-team10 pull request #33
Opened 2024-06-17 08:22 UTC by syu-kwsk

## Issue 番号

close #25 

## PRの概要
### 現状

ユーザ登録機能

### 今回やったこと

ユーザ登録
テスト

### やらなかったこと

### 動作検証

### チェックリスト

- [ ] CIをPassしましたか？ 

## 資料

## レビュワーへの共有事項

2024-06-17 08:38 UTC, aki-nishikawa requested changes
コメントした

2024-06-17 08:38 UTC, aki-nishikawa commented on backend/internal/usecases/signup_usecase.go
> +	}
ここで 2 点コメント

- err のハンドリングでネストしたくない
- mysql 関連のエラーをハンドリングするのは repository 層でやりたい

2024-06-17 09:30 UTC, syu-kwsk commented on backend/internal/usecases/signup_usecase.go
> +	}
あざ

2024-06-17 09:31 UTC, aki-nishikawa commented on backend/internal/usecases/signup_usecase.go
> +	}
俺が直した

2024-06-17 09:31 UTC, aki-nishikawa approved these changes
直した

2024-06-18 04:15 UTC, ry-na approved these changes
軽微なコメントしましたが[Should]未満なのでLGTM!

2024-06-18 04:15 UTC, ry-na commented on backend/internal/repositories/user_repository.go
> +			case 1062:
[Could]
ここの`1062`って数字のベタ書きできれば辞めたいかも！gorm(だよね？)が定数として持ってるなら使いたいんだけど、パッと見見当たらなかったのでutilとかにまとめられると良さそう！(別でエラーコード書くタイミングで良さそうではある)

2024-06-18 04:15 UTC, ry-na commented on backend/internal/repositories/user_repository.go
> +	if result.Error != nil {
[Could]
Goっぽくない書き方な気がするけど、こんな感じで先にreturnするとネストが減って読みやすいかも？
```
if result.Error == nil {
    return convertUserModelToEntity(&user), nil
}
```

2024-06-18 04:21 UTC, merged