パスワードをハッシュ化してDBに保存
givery-bootcamp/dena-2024-team10 pull request #45
Opened 2024-06-18 08:01 UTC by syu-kwsk

## Issue 番号

## PRの概要
### 現状

DBにハッシュ化したパスワードを保存
### 今回やったこと

ハッシュ化ロジックを追加した

### やらなかったこと

テストが書けてない

### 動作検証

### チェックリスト

- [ ] CIをPassしましたか？ 

## 資料

## レビュワーへの共有事項

2024-06-24 05:47 UTC, ry-na reviewed
一点コメントしたので修正をお願いしたいです！
今更だけど、こんな感じでタグ付けしてます！
- 直して欲しい(度合い)
  - Must > Should > Could
- その他単語の意味で、修正希望とは限らないやつ
  - Question, Coomment

2024-06-24 05:47 UTC, ry-na commented on backend/internal/usecases/signup_usecase.go
> +		return nil, err
[Should]
エラーハンドリング、西川が作ってくれた形式で書いて欲しい！

2024-06-24 05:47 UTC, ry-na commented on backend/test/usecases/signin_usecase_test.go
> +				&entities.User{Username: "test_username", Password: "$2a$10$V1L7LAkSxHSsmVuBgX7WU.tlnXqGcCO0v.W9BISf6eoP3XrwzWCsG"},
[Could]
コメントで元パスワード載せておくか、bcrypt関数をここで呼ぶと読みやすいかも！

2024-06-24 05:47 UTC, ry-na commented on backend/internal/usecases/signin_usecase.go
> +	if err != nil {
[Should]
エラーハンドリング、西川が作ってくれた形式で書いて欲しい！

2024-06-24 07:09 UTC, aki-nishikawa reviewed
全体的に名取くんに同意です！
あと、bcrypto の資料とかあったら PR にリンク貼ってくれると助かる！

2024-06-26 08:54 UTC, syu-kwsk commented on backend/internal/usecases/signin_usecase.go
> +	if err != nil {
errを返すで良さそう！

2024-06-26 09:53 UTC, aki-nishikawa requested changes
コメントした！

2024-06-26 09:53 UTC, aki-nishikawa commented on backend/internal/usecases/signin_usecase.go
> +		return nil, "", err
Must
ここのエラーはパスワードの比較やから SigninFailed で返してほしい！

2024-06-27 01:27 UTC, syu-kwsk commented on backend/internal/usecases/signin_usecase.go
> +		return nil, "", err
変更したぜ！！

2024-06-27 01:30 UTC, aki-nishikawa approved these changes
LGMT !!

2024-06-27 02:30 UTC, ry-na approved these changes
LGTM!

2024-06-27 02:31 UTC, merged