WIP #38 投稿作成APIを実装した
givery-bootcamp/dena-2024-team10 pull request #59
Opened 2024-06-25 08:05 UTC by ry-na

## Issue 番号
#38

## PRの概要
### 現状
投稿を作成できない

### 今回やったこと
投稿作成APIを作成した

### やらなかったこと

### 動作検証
```
curl -H "Content-Type: application/json" -b cookie.txt -d '{"title":"テスト投稿2", "body":"ほげほげ〜！"}' http://localhost:9000/post

[{"id":34,"title":"テスト投稿2","body":"ほげほげ〜！","user_id":1,"username":"","created_at":"","updated_at":""}]%
````
<img width="545" alt="image" src="https://github.com/givery-bootcamp/dena-2024-team10/assets/21969328/4f9106b5-a9b2-465a-bf8d-b21e7635ab9b">

### チェックリスト

- [ ] CIをPassしましたか？ 

## 資料

## レビュワーへの共有事項

2024-06-26 03:06 UTC, aki-nishikawa requested changes
コメントした

2024-06-26 03:06 UTC, aki-nishikawa commented on backend/internal/repositories/post_repository.go
> -		UpdatedAt: v.UpdatedAt,
上に同じで、 #46 を参考にするとやりやすそう

2024-06-26 08:50 UTC, ry-na commented on backend/internal/repositories/post_repository.go
> -	UpdatedAt string
口頭でも話した通り、#63 を取り込む形で修正しました！

2024-06-26 08:51 UTC, ry-na commented on backend/internal/controllers/schema/create_post_request.go
賛成です！修正しました！[1ade56d](https://github.com/givery-bootcamp/dena-2024-team10/pull/59/commits/1ade56dac17ee27106fed0650ec6890bae042f9d)(脳内が1file1structになってた)

2024-06-26 09:41 UTC, ry-na commented on backend/internal/usecases/create_post_usecase.go
> +	}
修正しました！[615b246](https://github.com/givery-bootcamp/dena-2024-team10/pull/59/commits/615b246add2bb073d1a44b439c1ca86b25677beb)
create_post_usecaseはrepositoryの呼び出ししかしてないのでテスト要らなくね？の気持ちで消してしまったので、問題ありそうならコメントください🙏(https://github.com/givery-bootcamp/dena-2024-team10/pull/59/commits/3fc19f50ce6919a3cd122d4baaff55582f65bd95)

2024-06-26 09:42 UTC, ry-na commented on backend/internal/repositories/post_repository.go
> -		UpdatedAt: v.UpdatedAt,
口頭でも話した通り、https://github.com/givery-bootcamp/dena-2024-team10/pull/63 を取り込む形で修正しました！

2024-06-27 01:42 UTC, syu-kwsk approved these changes
＊のやつは修正が必要そう！

2024-06-27 01:42 UTC, syu-kwsk commented on backend/internal/repositories/model/post.go
> +	DeletedAt *time.Time `gorm:"column:deleted_at"`
これは＊いらなそう

2024-06-27 01:42 UTC, syu-kwsk commented on backend/internal/repositories/post_repository.go
> +	return []*entities.Post{model.ConvertPostModelToEntity(&post)}, nil
戻り値はPost単体でいいんちゃうかな
Postを複数投稿するなら引数も変えないといけなそう

2024-06-27 01:42 UTC, syu-kwsk commented on backend/internal/controllers/post_controller.go
> +		ctx.Error(exception.ErrNotFound)
NotFoundよりなんかCreateFaildとかの方がいい？
それか、PostでCreateしたのにresultがnilやったらInternal ServerErrorかもね
ちょっとわかんない

2024-06-27 01:42 UTC, syu-kwsk commented on backend/internal/usecases/create_post_usecase.go
> +	}
postが返らないのは、コントローラじゃなくてusecaseでハンドリングしてもいいんかも
コントローラに書いてるのをこっちに追加するイメージ

2024-06-27 01:48 UTC, aki-nishikawa requested changes
コメントした！

2024-06-27 01:48 UTC, aki-nishikawa commented on backend/internal/interfaces/post_repository_interface.go
> +	CreatePost(title string, body string, userId int64) ([]*entities.Post, error)
ここも返り値が Post 単体かな

2024-06-27 01:48 UTC, aki-nishikawa commented on backend/internal/usecases/create_post_usecase.go
> +	post, err := u.postRepository.CreatePost(request.Title, request.Body, userId)
repository の結果をハンドリングすることがなさそうやから、そのまま return していいかも
```suggestion
	return u.postRepository.CreatePost(request.Title, request.Body, userId)
```

2024-06-27 01:48 UTC, aki-nishikawa commented on backend/internal/controllers/post_controller.go
> +		ctx.Error(exception.ErrNotFound)
Post が nil になるシチュエーションが今回やと考えられんから、 result == nil のエラーハンドリングそのものが不要かも

2024-06-27 02:03 UTC, ry-na commented on backend/internal/repositories/model/post.go
> +	DeletedAt *time.Time `gorm:"column:deleted_at"`
ここの*が無いとinsert時に`deleted_at`のデフォルト値が入ってきちゃうので、このままで行きます！(もっといい方法ありそうだけど)

2024-06-27 02:16 UTC, ry-na commented on backend/internal/usecases/create_post_usecase.go
> +	}
> Post が nil になるシチュエーションが今回やと考えられんから、 result == nil のエラーハンドリングそのものが不要かも

おっしゃる通りだったけど、今回はcontrollerのハンドリングを消したのでスルーします！

2024-06-27 02:19 UTC, ry-na commented on backend/internal/repositories/post_repository.go
> +	return []*entities.Post{model.ConvertPostModelToEntity(&post)}, nil
修正しました！

2024-06-27 02:20 UTC, ry-na commented on backend/internal/controllers/post_controller.go
> +		ctx.Error(exception.ErrNotFound)
エラーハンドリングを削除しました！

2024-06-27 02:20 UTC, ry-na commented on backend/internal/interfaces/post_repository_interface.go
> +	CreatePost(title string, body string, userId int64) ([]*entities.Post, error)
修正しました！

2024-06-27 02:22 UTC, ry-na commented on backend/internal/usecases/create_post_usecase.go
> +	post, err := u.postRepository.CreatePost(request.Title, request.Body, userId)
おっしゃる通りでマジで何もしてないコードだったね...
修正しました！

2024-06-27 02:31 UTC, syu-kwsk approved these changes
LGTM

2024-06-27 02:39 UTC, aki-nishikawa approved these changes
良さそう

2024-06-27 02:39 UTC, merged