WIP: Feature/comments
givery-bootcamp/dena-2024-team10 pull request #62
Opened 2024-06-25 09:20 UTC by wattah1002

## Issue 番号

## PRの概要
### 現状

### 今回やったこと

### やらなかったこと

### 動作検証

### チェックリスト

- [ ] CIをPassしましたか？ 

## 資料

## レビュワーへの共有事項

2024-06-27 11:10 UTC, shunsuke-tamura requested changes

2024-06-27 11:10 UTC, shunsuke-tamura commented on frontend/app/routes/posts.$postId.tsx
> +					{dialog}
dialogがここにいるのはあんま良くない気がする
このdialogは他の全要素の上に重なる形で出現するようにしたくて、ここに置いちゃうと、削除を押したコメントの`li`タグの中でdialog展開しちゃうから、順番がそれ以降の`li`の方が上になってしまう

だから、挙動的には、でたdialogの上にそれ以降の`li`が描画される。。。と思ったんだけど、なんか不思議な挙動した

https://github.com/givery-bootcamp/dena-2024-team10/assets/74412997/faabdf78-a573-43f6-96f1-b57977e82156

opacityを指定しているcreated_atだけなぜか上に被さるように表示された
試しに、`li`タグにopacityつけてみたら、中身全部dialogの上に表示されたわ
不思議な挙動だ。。。。

なんでこんなことになるんかはわからんけど、とりあえずdialogはページの一番下に宣言した方がいいと思います！
(Observableの下当たりかな)

そうなると、PostsDetailsの中でuseDialog使うことになると思うので、投稿を削除する方のdialogでできちゃうんじゃないかと思います

だから、CommentコンポーネントのPropsにconfirmを受け取るように変えて、Commentコンポーネント使ってるとこでPostDetailの方で宣言されてるconfirmを渡してあげて、今PostDetailの方で宣言されてるdialogを一番下にもっていったら、いい感じにできと思う！

2024-06-27 11:10 UTC, shunsuke-tamura commented on frontend/app/routes/posts.$postId.tsx
> +					onChange={(e) => setComment(e.target.value)}
今、コメントを投稿しても、inputの中身が空にならないようになってるみたい

```tsx
value={comment}
onChange={(e) => setComment(e.target.value)}
```

ってのを追加してあげると、`onSubmit={() => setComment("")}`がいい感じに反映されてinputの中身がリセットされるよ

2024-06-28 01:25 UTC, wattah1002 commented on frontend/app/routes/posts.$postId.tsx
> +					{isLastChild && <hr className={classNames("mt-4")} />}
確かに！ありがとうございますmm

2024-06-28 01:27 UTC, wattah1002 commented on frontend/app/routes/posts.$postId.tsx
> +					{isLastChild && <hr className={classNames("mt-4")} />}
35fd7a4c9af1f89a657d8605bee444f6a65ac687 で修正

2024-06-28 01:37 UTC, SIY1121 commented on frontend/app/routes/posts.$postId.tsx
> +					{dialog}
opacityで重ね合わせ順序変わるのはStackingContextの仕様です〜〜
https://developer.mozilla.org/ja/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context

dialogのレンダリング位置に振り回されたくないならReactPortalを使うのが正攻法だと思います（今回は既存dialogの再利用でも良いと思う！）

2024-06-28 01:40 UTC, wattah1002 commented on frontend/app/routes/posts.$postId.tsx
> +					{dialog}
確認ありがとう！不思議な挙動だ...

2024-06-28 01:43 UTC, wattah1002 commented on frontend/app/routes/posts.$postId.tsx
> +					{dialog}
c44231e41550557d8df8f7cf7a20934fcc76b2ab で修正

<img width="789" alt="image" src="https://github.com/givery-bootcamp/dena-2024-team10/assets/62461295/4490eba2-3634-447d-9b51-e13a874f6995">

2024-06-28 01:46 UTC, wattah1002 commented on frontend/app/routes/posts.$postId.tsx
> +					{dialog}
> opacityで重ね合わせ順序変わるのはStackingContextの仕様です〜〜
なるほど、、！

2024-06-28 01:50 UTC, wattah1002 commented on frontend/app/routes/posts.$postId.tsx
> +					onChange={(e) => setComment(e.target.value)}
ありがとう！
8c98641bfba141f0299770b4167dbb3e5eb4508e で修正

2024-06-28 02:01 UTC, shunsuke-tamura approved these changes
LGTM!!!

2024-06-28 07:58 UTC, SIY1121 approved these changes
🙏

2024-06-28 08:05 UTC, merged