WIP: Close #37 投稿更新APIを実装した
givery-bootcamp/dena-2024-team10 pull request #83
Opened 2024-06-27 07:32 UTC by ry-na

## Issue 番号
#37

## PRの概要
### 現状

### 今回やったこと

### やらなかったこと

### 動作検証

### チェックリスト

- [ ] CIをPassしましたか？ 

## 資料

## レビュワーへの共有事項

2024-06-27 08:53 UTC, syu-kwsk approved these changes
LGTM

2024-06-27 09:30 UTC, aki-nishikawa requested changes
動作確認の返り値で、Userが空になってそう

2024-06-27 09:30 UTC, aki-nishikawa commented on backend/internal/usecases/update_post_usecase.go
> +	}
GetById は post 見つからん時に nil, nil で返るから、こんな感じのエラーハンドリングなりそう
```suggestion
	post, err := u.postRepository.GetById(postId)
	if err != nil {
		return nil, err
	} else if post == nil {
	        return nil, exception.ErrPostNotFound
	}
```

2024-06-28 01:47 UTC, ry-na commented on backend/internal/usecases/update_post_usecase.go
> +	}
修正しました！ [265f281](https://github.com/givery-bootcamp/dena-2024-team10/pull/83/commits/265f2814fec9d3ad0647d9365181d7515a03ec0c)
ここ、本来は昨日Zoomで話した、「repositoryのpost not foundをusecaseでErrorとして返したい」みたいに言ってた所に対応したかったので適切な場所へ書き直しました！

2024-06-28 01:51 UTC, syu-kwsk approved these changes
LGTM

2024-06-28 02:26 UTC, aki-nishikawa requested changes

2024-06-28 02:26 UTC, aki-nishikawa commented on backend/internal/usecases/update_post_usecase.go
> +	}
ここのエラーハンドリングは以下で良さそう

```suggestion
	updatedPost, err := u.postRepository.UpdatePost(request.Title, request.Body, userId)
	if err != nil {
		return nil, err
	}
```

> 「repositoryのpost not foundをusecaseでErrorとして返したい」

この話やねんけど、どこでハンドリングするかって問題はあって悩みどころなのよね。
この usecase やと、repo.UpdatePost を呼び出す前に repo.GetById してるから、ビジネスロジック的には UpdatePost で "post not found" が返ってくることはありえへんねんな。
やから、ここで "post not found" が返ってきた場合は Internal ServerError が適切になるはずなんよ。

逆に、上の GetById はビジネスロジックとして、Post の存在を確認してるから "post not found" が発生したら専用のエラーを返したいって感じ

2024-06-28 02:33 UTC, aki-nishikawa approved these changes
azamasu !!!

2024-06-28 02:33 UTC, merged